### ISSUE TITLE
I hate this

### ISSUE THREAD

**Issue by Ralakimus** [sonicthedutchhedgehog/sonic-1-github-madness#11]
I've made some shit in my time, but this really takes the cake on the worst ROM hack I have ever seen.

Fuck you.

**Comment by derpguy125** [comment]
cry about it

**Comment by Min3rREALS** [comment]
wdym this is the greatest rom hack ever made

**Comment by derpguy125** [comment]
of course the guy who made crazysonic and s2 forces edition wouldnt understand the complexities of a rom hack made to be the absolute worst of the worst

**Comment by Ralakimus** [comment]
lol

**Comment by derpguy125** [comment]
im sorry ralakimus it was only a joke

a bad one

**Comment by Ralakimus** [comment]
it's no big deal, is all good

**Comment by SirFloofTheGithub** [comment]
> I've made some shit in my time, but this really takes the cake on the worst ROM hack I have ever seen.
> 
> Fuck you.

couldnt handle the trolla
cry bout it
